users_file = "users.txt"
log_level = "debug"
cookie_domain = "nginx.lan"
router_address = "root@satellite.lan"

[allowed_routes]
"/" = ["*"]
"/landing" = ["*"]
"/router_admin" = ["desktop"]

[allowed_subdomains]
"incus" = ["desktop"]
"forgejo" = ["desktop", "laptop"]
"vaultwarden" = ["*"]