[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
bcrypt.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
time.workspace = true