#users_file = "/etc/dashboard-web/users.txt"
users_file = "package/users.txt"
log_level = "trace"
cookie_domain = ""
secure_cookies = false
static_folder = "static"

[access_rules]
"/" = ["*"]
"/static/css/" = ["*"]
"/action_dashboard/cmd/router_poweroff" = ["admin"]
"incus@/" = ["desktop"]
"forgejo@/" = ["desktop", "laptop"]
"vaultwarden@/" = ["*"]
"vaultwarden@/admin" = ["desktop"]

[external_links]
"Incus" = "https://incus.nginx.lan"
"Forgejo" = "https://forgejo.nginx.lan"
"Vaultwarden" = "https://vaultwarden.nginx.lan"

[admin_commands]
[admin_commands.hosts]
local = ""
router = "root@satellite.lan"

[admin_commands.panels]
main_panel = "Main Panel"
router_panel = "Router Panel"

[admin_commands.commands]
update_dashboard = { name = "Update Dashboard", host = "local", panel = "main_panel", command = "/usr/local/bin/update_dashboard.sh" }
stats = { name = "Router Statistics", host = "router", panel = "router_panel", command = "stats" }
router_reboot = { name = "Reboot Router", host = "router", panel = "router_panel", command = "reboot" }
router_poweroff = { name = "Power Off Router", host = "router", panel = "router_panel", command = "poweroff" }
