users_file = "/etc/home-webserver/users.txt"
log_level = "info"
cookie_domain = "nginx.lan"
router_address = "root@satellite.lan"

[allowed_routes]
"/" = ["*"]
"/landing" = ["*"]
"/router_admin" = ["desktop"]

[allowed_subdomains]
"incus" = ["desktop"]
"forgejo" = ["desktop", "laptop"]
"vaultwarden" = ["*"]

[external_links]
"Incus" = "https://incus.nginx.lan"
"Forgejo" = "https://forgejo.nginx.lan"
"Vaultwarden" = "https://vaultwarden.nginx.lan"