# This configuration file is read at startup
# In case of change, you must restart the application, this will expire all authentication cookie, making a new login required
# If you changed only the passwords, you cann send SIGHUP to reload the users and passwords without restarting

log_level = "info"
cookie_domain = "nginx.lan"
secure_cookies = true
cookie_duration = 24 # in hours
static_folder = "/etc/dashboard-web/static"
users_db = "/etc/dashboard-web/users_db.txt" # Don't have to exist on first launch


[access_rules]
"/" = ["*"]
"/static/css/" = ["*"]

[external_links]

[admin_commands]
[admin_commands.hosts]

[admin_commands.panels]

[admin_commands.commands]
