[package]
name = "utils"
version = "0.0.0"
edition = "2024"

[dependencies]
app_errors.workspace = true

serde.workspace = true
time.workspace = true
tower-cookies.workspace = true
url.workspace = true