name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Build for gnu and musl
      run: |
        mkdir bin
        # gnu
        cargo build --release --target x86_64-unknown-linux-gnu
        cp "target/x86_64-unknown-linux-gnu/release/dashboard-web" "bin/dashboard-web-linux-gnu"
        # musl
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-unknown-linux-musl
        cp "target/x86_64-unknown-linux-musl/release/dashboard-web" "bin/dashboard-web-linux-musl"
        
    - name: Upload Assets to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch --prune --unshallow --tags
        TAG_NAME=$(git describe --tags --abbrev=0)
        gh release upload "$TAG_NAME" bin/* --clobber
